---
kind: Namespace
apiVersion: v1
metadata:
  name: data-storing
---
apiVersion: v1
kind: Service
metadata:
  name: data-storing
  labels:
    app: data-storing
    service: data-storing
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: data-storing
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: data-storing
  labels:
    account: data-storing
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-storing
  labels:
    app: data-storing
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-storing
      version: v1
  template:
    metadata:
      labels:
        app: data-storing
        version: v1
    spec:
      serviceAccountName: data-storing
      containers:
        - name: data-storing
          image: quay.io/gfulton/data-storing:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---