- op: replace
  path: /metadata/name
  value: data-clean
- op: replace
  path: /metadata/namespace
  value: data-clean
- op: replace
  path: /metadata/labels/account
  value: data-clean
- op: replace
  path: /metadata/labels/app
  value: data-clean
- op: replace
  path: /metadata/labels/version
  value: v1
- op: replace
  path: /spec/output/to/name
  value: data-clean:latest
- op: replace
  path: /spec/strategy/sourceStrategy/from/namespace
  value: data-clean