apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./data-analysis
  - ./data-cleaning
  - ./data-collection
  - ./data-evaluation
  - ./data-metadata
  - ./data-preparation
  - ./data-query
  - ./data-splitting
  - ./data-storage
  - ./data-transformation
  - ./data-validation
