---
kind: Namespace
apiVersion: v1
metadata:
  name: data-transforming
---
apiVersion: v1
kind: Service
metadata:
  name: data-transforming
  labels:
    app: data-transforming
    service: data-transforming
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: data-transforming
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: data-transforming
  labels:
    account: data-transforming
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-transforming
  labels:
    app: data-transforming
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-transforming
      version: v1
  template:
    metadata:
      labels:
        app: data-transforming
        version: v1
    spec:
      serviceAccountName: data-transforming
      containers:
        - name: data-transforming
          image: quay.io/gfulton/data-transforming:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---