---
kind: Namespace
apiVersion: v1
metadata:
  name: data-cleaning
---
apiVersion: v1
kind: Service
metadata:
  name: data-cleaning
  labels:
    app: data-cleaning
    service: data-cleaning
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: data-cleaning
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: data-cleaning
  labels:
    account: data-cleaning
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-cleaning
  labels:
    app: data-cleaning
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-cleaning
      version: v1
  template:
    metadata:
      labels:
        app: data-cleaning
        version: v1
    spec:
      serviceAccountName: data-cleaning
      containers:
        - name: data-cleaning
          image: quay.io/gfulton/data-cleaning:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---