---
kind: Namespace
apiVersion: v1
metadata:
  name: data-storage
---
apiVersion: v1
kind: Service
metadata:
  name: data-storage
  labels:
    app: data-storage
    service: data-storage
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: data-storage
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: data-storage
  labels:
    account: data-storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-storage
  labels:
    app: data-storage
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-storage
      version: v1
  template:
    metadata:
      labels:
        app: data-storage
        version: v1
    spec:
      serviceAccountName: data-storage
      containers:
        - name: data-storage
          image: quay.io/gfulton/data-storage:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---