- op: replace
  path: /metadata/name
  value: data-metadata
- op: replace
  path: /metadata/namespace
  value: data-metadata
- op: replace
  path: /metadata/labels/account
  value: data-metadata
- op: replace
  path: /metadata/labels/app
  value: data-metadata
- op: replace
  path: /metadata/labels/version
  value: v1
- op: replace
  path: /spec/output/to/name
  value: data-metadata:latest
