apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: patch-metadata-name
  namespace: patch-metadata-namespace
  labels:
    account: patch-metadata-labels-account
    app: patch-metadata-labels-app
    version: patch-metadata-labels-version
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
      - "*"
