apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service-account.yaml
  - destination-rule.yaml
  - deployment.yaml
  - service.yaml
  - gateway.yaml
  - virtual-service.yaml
