apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: patch-metadata-name
  namespace: patch-metadata-namespace
spec:
  hosts:
    - patch-virtual-service-spec-hosts-0
  gateways:
    - patch-virtual-service-spec-gateways-0
  http:
    - match:
        - uri:
            exact: patch-virtual-service-spec-http-0-route-0-uri-exact
      route:
        - destination:
            host: patch-virtual-service-spec-http-0-route-0-destination-host
            port:
              number: patch-virtual-service-spec-http-0-route-0-destination-port-number