apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../bases
patches:
  - path: patch-metadata.yaml
    target:
      kind: ServiceAccount
  - path: patch-service-account.yaml
    target:
      kind: ServiceAccount
  - path: patch-destination-rule.yaml
    target:
      kind: DestinationRule
  - path: patch-metadata.yaml
    target:
      kind: DestinationRule
  - path: patch-deployment.yaml
    target:
      kind: Deployment
  - path: patch-metadata.yaml
    target:
      kind: Deployment
  - path: patch-service.yaml
    target:
      kind: Service
  - path: patch-metadata.yaml
    target:
      kind: Service
  - path: patch-metadata.yaml
    target:
      kind: Gateway
  - path: patch-metadata.yaml
    target:
      kind: VirtualService
  - path: patch-virtual-service.yaml
    target:
      kind: VirtualService