---
kind: Namespace
apiVersion: v1
metadata:
  name: data-labeling
---
apiVersion: v1
kind: Service
metadata:
  name: data-labeling
  labels:
    app: data-labeling
    service: data-labeling
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: data-labeling
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: data-labeling
  labels:
    account: data-labeling
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-labeling
  labels:
    app: data-labeling
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-labeling
      version: v1
  template:
    metadata:
      labels:
        app: data-labeling
        version: v1
    spec:
      serviceAccountName: data-labeling
      containers:
        - name: data-labeling
          image: quay.io/gfulton/data-labeling:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---