apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../bases
patches:
  - path: patch-namespace.yaml
    target:
      kind: Namespace
  - path: patch-service-account.yaml
    target:
      kind: ServiceAccount
  - path: patch-destination-rule.yaml
    target:
      kind: DestinationRule
  - path: patch-service.yaml
    target:
      kind: Service
  - path: patch-build-config.yaml
    target:
      kind: BuildConfig
  - path: patch-deployment.yaml
    target:
      kind: Deployment