- op: replace
  path: /metadata/name
  value: data-analysis
- op: replace
  path: /metadata/labels/account
  value: data-analysis
- op: replace
  path: /metadata/labels/app
  value: data-analysis
- op: replace
  path: /metadata/namespace
  value: data-analysis
- op: replace
  path: /spec/selector/matchLabels/app
  value: data-analysis
- op: replace
  path: /spec/selector/matchLabels/deployment
  value: data-analysis
- op: replace
  path: /spec/selector/matchLabels/version
  value: v1
- op: replace
  path: /spec/template/metadata/labels/app
  value: data-analysis
- op: replace
  path: /spec/template/metadata/labels/deployment
  value: data-analysis
- op: replace
  path: /spec/template/metadata/labels/version
  value: v1
- op: replace
  path: /spec/template/spec/containers/0/name
  value: data-analysis
