{{- if .Values.serviceMeshControlPlane.create -}}
apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: {{ template "service-mesh.namespace" . }}
  namespace: {{ template "service-mesh.namespace" . }}
spec:
  version: v2.0
  tracing:
    type: Jaeger
    sampling: 10000
  addons:
    jaeger:
      name: jaeger
      install:
        storage:
          type: Memory
    kiali:
      enabled: true
      name: kiali
    grafana:
      enabled: true
{{- end }}