---
kind: Namespace
apiVersion: v1
metadata:
  name: data-analysis
---
apiVersion: v1
kind: Service
metadata:
  name: data-analysis
  labels:
    app: data-analysis
    service: data-analysis
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: data-analysis
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: data-analysis
  labels:
    account: data-analysis
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    app.openshift.io/vcs-url: https://github.com/cgfulton/mlops-quarkus.git
    app.quarkus.io/vcs-url: https://github.com/cgfulton/mlops-quarkus.git
  labels:
    app.kubernetes.io/name: data-analysis
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.openshift.io/runtime: quarkus
  name: data-analysis
spec:
  replicas: 1
  selector:
    app.kubernetes.io/name: data-analysis
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.openshift.io/runtime: quarkus
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        app.openshift.io/vcs-url: https://github.com/cgfulton/mlops-quarkus.git
        app.quarkus.io/vcs-url: https://github.com/cgfulton/mlops-quarkus.git
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: data-analysis
        app.openshift.io/runtime: quarkus
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
      namespace: data-analysis
    spec:
      containers:
        - args:
            - -Dquarkus.http.host=0.0.0.0
            - -Djava.util.logging.manager=org.jboss.logmanager.LogManager
            - -jar
            - /deployments/quarkus-run.jar
          command:
            - java
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: JAVA_APP_JAR
              value: /deployments/quarkus-run.jar
          image: image-registry.openshift-image-registry.svc:5000/data-analysis/data-analysis:1.0.0-SNAPSHOT
          imagePullPolicy: IfNotPresent
          name: data-analysis
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
          - data-analysis
        from:
          kind: ImageStreamTag
          name: data-analysis:1.0.0-SNAPSHOT
          namespace: data-analysis
      type: ImageChange