apiVersion: v1
kind: Service
metadata:
  name: data-analysis
  namespace: data-analysis
  labels:
    app: data-analysis
    service: data-analysis
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: data-analysis

