apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../data-base
resources:
  - ingress.yaml
patches:
  - path: patch-subscription.yaml
    target:
      kind: ServiceAccount
  - path: patch-destination-rule.yaml
    target:
      kind: DestinationRule