---
namespace:
  name: "some_service_mesh"
  create: true

serviceMeshControlPlane:
  create: true

serviceMeshMember:
  create: true

serviceMeshMemberRoll:
  create: true

members:
  - data-analysis
  - data-collect
  - data-extract
  - data-metadata
  - data-query
  - data-storage
  - data-validate
  - data-clean
  - data-evaluate
  - data-ingress
  - data-prepare
  - data-split
  - data-transform
