apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  generation: 4
  labels:
    app: patch-metadata-labels-app
    version: patch-metadata-labels-version
    account: patch-metadata-labels-account
  name: patch-metadata-name
  namespace: patch-metadata-namespace
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: patch-spec-output-to-name
  postCommit: {}
  resources:
    limits:
      cpu: "4"
      memory: 4Gi
  runPolicy: Serial
  source:
    contextDir: getting-started
    git:
      ref: main
      uri: https://github.com/quarkusio/quarkus-quickstarts.git
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: ubi-quarkus-native-s2i:20.3.1-java11
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
    - github:
        secret: SsUPlWXKdK153_MVXRIk
      type: GitHub
    - generic:
        secret: 4JzKz28VwEWtRjq8VwFW
      type: Generic
    - type: ConfigChange
    - imageChange:
        lastTriggeredImageID: quay.io/quarkus/ubi-quarkus-native-s2i@sha256:c8a7b0ece157b64ef00e2eb6219a271fcea90b8ca41448d5b07a234eac656f88
      type: ImageChange


